### ISSUE TITLE
make nasm dependency private

### ISSUE THREAD

**Issue by a-teammate** [lasote/conan-libjpeg-turbo#4]
could you make the nasm dependency private to the project?
 Otherwise it shows up when querying `conan info --only=license` for distribution purpose, which it shouldn't, or should it?

Btw: I just found about yasm, which is a replacement (?) for nasm it seems, but it has cmake support.

so maybe patching libjpeg-turbo to use yasm instead could also fix #3

**Comment by lasote** [comment]
Hi! @a-teammate, it would make sense, but libjpeg-turbo library doesn't depend on Nasm. ¿? Do you have any other dependency in your project that uses nasm? OpenSSL maybe?

**Comment by a-teammate** [comment]
It does in version 1.5.1

https://github.com/lasote/conan-libjpeg-turbo/blob/release/1.5.1/conanfile.py#L27

**Comment by lasote** [comment]
@a-teammate I'm pushing it. Thanks!
