### ISSUE TITLE
Compilation error on Ubuntu 16.04

### ISSUE THREAD

**Issue by phobos2077** [lasote/conan-libjpeg-turbo#6]
OS: Ubuntu 16.04 LTS x64
Generator: cmake
Compiler: clang

```
autoreconf: running: /usr/bin/autoconf --force
configure.ac:21: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

libjpeg-turbo/1.5.1@lasote/stable: ERROR: Package 'aa419b261886313e9c396a4c41c66904484aadb7' build failed
libjpeg-turbo/1.5.1@lasote/stable: WARN: Build folder /home/killian/.conan/data/libjpeg-turbo/1.5.1/lasote/stable/build/aa419b261886313e9c396a4c41c66904484aadb7
libjpeg-turbo/1.5.1@lasote/stable: WARN:   File "/home/killian/.conan/data/libjpeg-turbo/1.5.1/lasote/stable/export/conanfile.py", line 47, in build
libjpeg-turbo/1.5.1@lasote/stable: WARN:     self.run("cd %s && autoreconf -fiv" % self.ZIP_FOLDER_NAME)
libjpeg-turbo/1.5.1@lasote/stable: WARN:   File "conan/conans/model/conan_file.py", line 243, in run
libjpeg-turbo/1.5.1@lasote/stable: WARN: ConanException: Error 256 while executing cd libjpeg-turbo-1.5.1 && autoreconf -fiv
ERROR: libjpeg-turbo: Error 256 while executing cd libjpeg-turbo-1.5.1 && autoreconf -fiv
```

**Comment by lasote** [comment]
Try ``brew install libtool``

**Comment by lasote** [comment]
Try `sudo apt-get install libtool`

**Comment by phobos2077** [comment]
Yes I figured to install a bunch of additional packages to compile some of these libraries. Is it considered norm for such requirements? 
Note that I'm a new to linux so I expect software to work, or at least, to provide some instructions on how to make it work. 

I think I saw some of the Conan packages (was it glew?) to check if required apt package is installed and prompt to install it before proceeding. Maybe the same can be done in this case as the required software is not included by default in what I understand as one of the most popular OSes.

**Comment by lasote** [comment]
Conan usually doesn't take care of the build tools needed for building the packages, ``libtool`` is a very common tool almost found in every linux system and needed for building from sources hundreds of libraries, so I think introduce that complexity in the conan recipes is too much.
